context:
  dataset_name: "MetroPT3"
  model_name: "IForest"
  xai_method_name: "LIME"
  device: "cpu"
  model_path: "examples/models/MetroPT3/IForest/MetroPT3_IForest_seed_0.pkl"
  X_test_path: "examples/datasets/MetroPT3/X_test.csv"
  y_test_path: "examples/datasets/MetroPT3/y_test.csv"
  attributions_path: "examples/attributions/MetroPT3/IForest/LIME/MetroPT3_IForest_lime_attributions.csv"
  X_background_path: "examples/datasets/MetroPT3/X_background.csv"
  y_background_path: "examples/datasets/MetroPT3/y_background.csv"
  X_batch_path: "examples/datasets/MetroPT3/X_batch.csv"
  y_batch_path: "examples/datasets/MetroPT3/y_batch.csv"

metrics:
  - name: Complexity
    params:
      normalise: true

  - name: Sparseness
    params:
      normalise: true

  - name: Consistency
    params:
      abs: false
      normalise: true

  - name: FaithfulnessEstimate
    params:
      features_in_step: 1
      abs: false
      normalise: true
      perturb_baseline: mean

  - name: Faithfulness
    params:
      base_strategy: mean

  - name: MonotonicityCorrelation
    params:
      eps: 1e-5
      nr_samples: 100
      features_in_step: 1
      abs: true
      normalise: true
      perturb_baseline: mean

  - name: MonotonicityMetric
    params:
      base_strategy: mean

  - name: Monotonicity
    params:
      features_in_step: 1
      abs: true
      normalise: true
      perturb_baseline: black

  - name: SensitivityN
    params:
      n_max_percentage: 1.0
      features_in_step: 1
      abs: false
      normalise: true
      perturb_baseline: uniform

  - name: Sufficiency
    params:
      threshold: 0.6
      distance_func: seuclidean
      abs: true
      normalise: true

  - name: AvgSensitivity
    params:
      nr_samples: 20
      abs: false
      normalise: false
      lower_bound: 0.2

  - name: LocalLipschitzEstimate
    params:
      nr_samples: 20
      abs: false
      normalise: true
      perturb_mean: 0.0
      perturb_std: 0.1

  - name: MaxSensitivity
    params:
      nr_samples: 20
      abs: false
      normalise: false
      lower_bound: 0.2

  - name: RelativeInputStability
    params:
      nr_samples: 20
      abs: false
      normalise: false

  - name: RelativeOutputStability
    params:
      nr_samples: 20
      abs: false
      normalise: false

  - name: Completeness
    params:
      abs: false
      normalise: true

  - name: NonSensitivity
    params:
      eps: 1e-5
      features_in_step: 1
      abs: true
      normalise: true
      perturb_baseline: black

explainers:
  - name: LIME
    params:
      mode: classification
      random_state: 42
      num_samples: 5000
      labels: [1]
      distance_metric: euclidean

  - name: SHAP
    params:
      mode: classification
      algorithm: auto
      max_background_samples: 100
      output_index: 1
      random_state: 42

  - name: BreakDown
    params:
      mode: classification
      output_index: 1
      random_state: 42

  - name: MAPLE
    params:
      mode: classification
      output_index: 1
      fe_type: rf
      n_estimators: 200
      max_features: 0.5
      min_samples_leaf: 10
      regularization: 0.001
      validation_size: 0.2
      random_state: 42
      n_jobs: -1
