# xai_metrics\metrics\robustness\average_stability.py
import numpy as np

from xai_metrics.base import BaseMetric, MetricContext, MetricSkipped, register_metric
from xai_metrics.base.types import ExplainFunc

from collections.abc import Callable
from typing import Mapping, Any, cast

@register_metric
class AverageStability(BaseMetric):
    """
    Average Stability robustness metric.

    This metric evaluates the sensitivity of an explanation to small
    perturbations of the input. For each observation, a set of neighbouring
    inputs is generated by adding random noise, their explanations are
    recomputed and the distance between each neighbouring explanation and the
    original explanation is measured.

    For each observation ``i``, neighbouring inputs are generated as:

        x_i^(j) = x_i + epsilon_j

    The explanation of each neighbouring input is then compared with the
    original explanation:

        d_i^(j) = d(phi(x_i^(j)), phi(x_i))

    where ``phi`` is the explanation function and ``d`` is the configured
    distance metric.

    The Average Stability score for observation ``i`` is:

        AS_i = (1 / K) * sum_j d_i^(j)

    where ``K`` is the number of sampled neighbours.

    The metric returns one Average Stability value per observation. Lower values
    are better: a small score indicates that nearby inputs produce similar
    explanations, suggesting that the explanation method is locally stable.

    The same set of random noise masks is reused for every evaluated observation,
    ensuring that all observations are evaluated using equivalent perturbation
    patterns.

    The implementation is based on the Average Sensitivity or Stability metric
    discussed by Bhatt et al. (2020) and follows the implementation provided by
    Xplique, with support for custom explanation functions, configurable distance
    metrics and reproducible perturbation sampling.

    Bhatt, U., Weller, A., & Moura, J. M. F. (2020).
    Evaluating and Aggregating Feature-based Model Explanations.
    Proceedings of the Twenty-Ninth International Joint Conference on
    Artificial Intelligence (IJCAI).
    """
    NAME = "AverageStability"

    def __init__(
        self,
        context: MetricContext,
        explain_func: ExplainFunc,
        params: Mapping[str, Any] | None = None
    ):
        """
        Parameters
        ----------
        context : MetricContext
            Shared metric evaluation context. It must contain the model,
            ``X_test``, selected observations and attribution values. ``y_test``
            may be ``None`` when the explanation function does not require
            explicit targets.
        explain_func : ExplainFunc
            Explanation function used to recompute attribution values for
            perturbed neighbouring inputs. It must accept the model, a batch of
            observations and their targets, and return one explanation per
            observation.
        params : Mapping[str, Any] or None, optional
            Metric-specific parameters. Supported keys are:

            - ``radius`` : float, optional
              Maximum absolute magnitude of the random perturbation. The default
              value is ``0.1``.

            - ``nb_samples`` : int, optional
              Number of neighbouring inputs generated for each observation. The
              default value is ``20``.

            - ``distance`` : {"l1", "l2"} or callable, optional
              Distance used to compare explanations. ``"l1"`` computes the sum
              of absolute differences and ``"l2"`` computes the Euclidean
              distance. A custom callable must return a scalar. The default
              value is ``"l2"``.

            - ``random_state`` : int, np.random.Generator or None, optional
              Random seed or NumPy random generator used for perturbation
              sampling. The default value is ``None``.

            - ``symmetric_noise`` : bool, optional
              Whether to sample perturbations from ``[-radius, radius]`` instead
              of ``[0, radius]``. The default value is ``False`` in order to
              reproduce the behaviour of Xplique.

            If ``None``, an empty dictionary is used.

        Raises
        ------
        ValueError
            If ``explain_func`` is ``None``.
        """
        super().__init__(context, params)

        if explain_func is None:
            raise ValueError("AverageStability requires 'explain_func' to be provided via dependencies.")

        self.explain_func = explain_func

    def run(self):
        """
        Compute the Average Stability metric.

        For every selected observation, neighbouring inputs are generated by
        adding random noise. Their explanations are recomputed using
        ``explain_func`` and compared with the original explanation.

        The score for each observation is the mean distance between its original
        explanation and the explanations of its sampled neighbours.

        Returns
        -------
        List[float]
            Average explanation distance for each evaluated observation. Lower
            values indicate more stable explanations.

        Raises
        ------
        MetricSkipped
            If no observations are selected.
        ValueError
            If the number or shape of the original explanations is incompatible
            with the selected inputs, if ``radius`` is negative, if
            ``nb_samples`` is not positive, if ``distance`` is invalid, if
            ``explain_func`` returns an invalid number or shape of explanations,
            or if a custom distance function does not return a scalar.

        Notes
        -----
        For ``distance="l1"``, the distance between two explanations is computed
        as the sum of their absolute element-wise differences.

        For ``distance="l2"``, the Euclidean distance between two explanations
        is computed.

        A custom distance callable receives the neighbouring explanation and the
        corresponding original explanation and must return a scalar value.

        The returned values are computed independently for each observation.
        Unlike the original Xplique implementation, they are not automatically
        averaged into a single dataset-level stability score.
        """
        ctx = self.context
        p = self.params

        inputs = np.asarray(
            ctx.X_test.loc[ctx.observations].to_numpy(dtype=np.float32, copy=True),
            dtype=np.float32
        )
        targets = None if ctx.y_test is None else np.asarray(ctx.y_test.loc[ctx.observations])

        explanations = np.asarray(ctx.attributions, dtype=np.float32)

        if len(inputs) == 0:
            raise MetricSkipped(f"{self.NAME} skipped: no observations were selected.")

        if len(explanations) != len(inputs):
            raise ValueError("The number of explanations must match the number of inputs.")

        radius = float(p.get("radius", 0.1))
        nb_samples = int(p.get("nb_samples", 20))
        distance = p.get("distance", "l2")
        random_state = p.get("random_state")
        symmetric_noise = bool(p.get("symmetric_noise", False))

        if radius < 0.0:
            raise ValueError("radius must be non-negative.")

        if nb_samples <= 0:
            raise ValueError("nb_samples must be positive.")

        if isinstance(distance, str):
            if distance not in ('l1', 'l2'):
                raise ValueError("distance must be 'l1', 'l2', or a callable.")
        elif callable(distance):
            distance = cast(Callable[[np.ndarray, np.ndarray], float], distance)
        else:
            raise ValueError("distance must be 'l1', 'l2', or a callable.")

        rng = random_state if isinstance(random_state, np.random.Generator) else np.random.default_rng(random_state)
        if symmetric_noise:
            low = -radius
            high = radius
        else:
            low = 0.0
            high = radius

        # These noise masks are created ones and reused for every observation
        noisy_masks = rng.uniform(low=low, high=high, size=(nb_samples, *inputs.shape[1:])).astype(np.float32)

        scores = []

        for index, (input_sample, explanation) in enumerate(zip(inputs, explanations)):
            neighbours = input_sample[None, ...] + noisy_masks

            neighbour_targets = (
                None
                if targets is None
                else np.repeat(
                    targets[index:index + 1],
                    nb_samples,
                    axis=0
                )
            )

            neighbour_explanations = np.asarray(
                self.explain_func(
                    ctx.model,
                    neighbours,
                    neighbour_targets
                ),
                dtype=np.float32
            )

            if len(neighbour_explanations) != nb_samples:
                raise ValueError("explain_func must return one explanation per neighbouring input.")

            if neighbour_explanations.shape[1:] != explanation.shape:
                raise ValueError(
                    "The explanations returned by explain_func must have the same feature shape as the original explanations. "
                    f"Expected {explanation.shape}, got {neighbour_explanations.shape[1:]}."
                )

            distances = []

            for neighbour_explanation in neighbour_explanations:
                if callable(distance):
                    value = distance(neighbour_explanation, explanation)
                elif distance == 'l1':
                    value = np.sum(np.abs(neighbour_explanation - explanation))
                else:
                    value = np.sqrt(np.sum((neighbour_explanation - explanation) ** 2))

                if not np.isfinite(value):
                    raise ValueError("The distance between explanations must be finite.")
                
                distances.append(float(value))
            scores.append(float(np.mean(distances)))

        return scores