context:
  device: "cpu"
  datasets_dir: "datasets"
  models_dir: "models"
  attributions_dir: "attributions"

metrics:
  - name: Complexity
    params:
      normalise: true

  - name: Sparseness
    params:
      normalise: true

  - name: Faithfulness
    params:
      base_strategy: mean

  - name: LocalLipschitzEstimate
    params:
      nr_samples: 200
      normalise: true

explainers:
  - name: LIME
    params:
      num_samples: 5000

  - name: SHAP
    params:
      max_background_samples: 100
      abs: true

  - name: BreakDown
    params:
      abs: true

  - name: MAPLE
    params:
      abs: true