context:
  device: "cpu"
  datasets_dir: "datasets"
  models_dir: "models"
  attributions_dir: "attributions"

metrics:
  - name: Complexity
    params:
      normalise: true

  - name: Sparseness
    params:
      normalise: true

  - name: Faithfulness
    params:
      base_strategy: mean

  - name: LocalLipschitzEstimate
    params:
      nr_samples: 200
      normalise: true

explainers:
  - name: LIME
    params:
      mode: classification
      random_state: 42
      num_samples: 5000
      labels: [1]
      distance_metric: euclidean

  - name: SHAP
    params:
      mode: classification
      algorithm: auto
      max_background_samples: 100
      output_index: 1
      abs: true
      random_state: 42

  - name: BreakDown
    params:
      mode: classification
      output_index: 1
      abs: true
      random_state: 42

  - name: MAPLE
    params:
      mode: classification
      output_index: 1
      fe_type: rf
      n_estimators: 200
      max_features: 0.5
      min_samples_leaf: 10
      regularization: 0.001
      validation_size: 0.2
      random_state: 42