# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

import os
import sys

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "../../..")))

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

project = 'XAI_metrics'
copyright = '2026, Maria Teresa Alba Rueda'
author = 'Maria Teresa Alba Rueda'

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
]

autoclass_content = "both"
autodoc_typehints = "description"
autodoc_typehints_format = "short"
autodoc_mock_imports = ["quantus", "xplique"]
napoleon_use_ivar = True

templates_path = ['_templates']
exclude_patterns = ["api/modules.rst", "api/xai_metrics.rst"]



# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

html_theme = "sphinx_rtd_theme"
html_static_path = ['_static']


autodoc_type_aliases = {
    "BaseMetric": "xai_metrics.base.base_metric.BaseMetric",
    "MetricContext": "xai_metrics.base.base_metric.MetricContext",
    "MetricSkipped": "xai_metrics.base.base_metric.MetricSkipped",
}


def skip_imported_members(app, what, name, obj, skip, options):
    """
    Avoid documenting objects re-exported from package ``__init__`` modules.

    API pages generated by sphinx-apidoc often document both a package and its
    submodules. If a package re-exports classes from a submodule, Sphinx creates
    duplicate Python targets such as ``xai_metrics.base.MetricContext`` and
    ``xai_metrics.base.base_metric.MetricContext``. Skipping imported members
    keeps the canonical target in the module where the object is defined.
    """
    current_module = app.env.temp_data.get("autodoc:module")
    object_module = getattr(obj, "__module__", None)

    if current_module and object_module and object_module != current_module:
        return True

    return skip


def setup(app):
    app.connect("autodoc-skip-member", skip_imported_members)
